jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - ninja-build

script:
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - cmake --build .
  - ctest
