os: linux

language: cpp

dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - ninja-build

script:
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - cmake --build .
  - ctest
