jobs:
  include:
    - os: linux
      dist: xenial
      compiler:
        - clang
        - gcc
    - os: linux
      dist: bionic
      compiler:
        - clang
        - gcc

language: cpp

addons:
  apt:
    packages:
      - ninja-build

script:
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - cmake --build .
  - ctest
