version: 2.1
executors:
  exectr:
    docker:
      - image: glyphrider/cpp:latest

jobs:
  build-clang:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir clang
            cd clang
            env CC=clang CXX=clang++ cmake -G Ninja ..
            ninja
      - persist_to_workspace:
          root: .
          paths: clang

  build-gcc:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir gcc
            cd gcc
            env CC=gcc CXX=g++ cmake -G Ninja ..
            ninja
      - persist_to_workspace:
          root: .
          paths: gcc

  test-clang:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd clang
            ./roman_tests --gtest_output=xml
      - store_test_results:
          path: clang

  test-gcc:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd gcc
            ./roman_tests --gtest_output=xml
      - store_test_results:
          path: gcc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-clang
      - build-gcc
      - test-clang:
          requires:
            - build-clang
      - test-gcc:
          requires:
            - build-gcc
